# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npx eslint .
    - run: npm test -- --passWithNoTests
    env:
        CI: true
